### ISSUE TITLE
当标题有三个的时候,首次点击第三个列表的项目会出现数据越界的崩溃错误

### ISSUE THREAD

**Issue by HughLi** [Ryan-Wong-iOS/RW_DropdownMenu#3]
当选择框生成三个title的时候,一开始就去点击第三个(最右侧的一个)下面的项目,会崩溃

**Comment by Ryan-Wong-iOS** [comment]
NSArray *_titleArray;
NSArray *_leftArray;
NSArray *_rightArray;
Demo 中，如果需要增加一个title的话，以上这个三个数组都需要增加；
不知道您是否有把这三个数组都添加了呢？

**Comment by HughLi** [comment]
都添加了  包括你自己的代码  当运行起来后  你直接去点第三个  选中里面任意选项 就会崩溃
